install-dependencies:
	${MAKE} -C ../.. install-dependencies

login-spn:
	${MAKE} -C infra/ login-spn

tf-init:
	${MAKE} -C infra/ tf-init

tf-import-rg:
	${MAKE} -C infra/ tf-import-rg

tf-plan:
	${MAKE} -C infra/ tf-plan

tf-apply:
	${MAKE} -C infra/ tf-apply